### PR TITLE
Create dashboard layout

### PR DESCRIPTION
**Pull request by sophiabulcock**
First draft of a skeleton for  the dashboard layout, using  the cars  data set as placeholders.

### CODE REVIEW

**Comment by WraySmith** [comment]
Looking on the right track for sure!

I think a couple things off the bat that are potentially worth trying to deal with (even if a rudimentary level include):
- Get the dropdowns onto a separated area on the left maybe something like [this](https://dash-gallery.plotly.host/dash-clinical-analytics/) one (although a much smaller width)
- figuring out how to extend the widths of the upper two graphs
- figuring out how to do the lower graphs so they're not scrolling and are aligned
- getting the range bars in there
- was thinking for the data description, could use a collapse/expand thing, not sure if this is the right [type of feature](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/collapse/), lots of options.

The additional resources sections of the lecture 3 notes seem like they have some good links. And the example app gallery has a lot of ideas too. Might be worth perusing a few examples and seeing what jumps at as useful features. Was just scrolling through the [bootstrap components section](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/alert/) and there's lots in there too!

**Comment by WraySmith** [comment]
I noticed the linter is failing, I pulled the code and was able to able to run the formatter on it and it solved a bunch but there were still some remaining warning some of which are related to the col width that @mqharris mentioned before so may be worth switching to the formatter he suggested. @mqharris can you remind us what that was - maybe see if you can pull the branch and run your formatter and see if it cleans up all the linter warning.

**Comment by WraySmith** [comment]
also, if the PR is just for getting the framework into your working dashboard branch, feel free to merge in as needed!

**Comment by WraySmith** [comment]
> The additional resources sections of the lecture 3 notes seem like they have some good links. And the example app gallery has a lot of ideas too. Might be worth perusing a few examples and seeing what jumps at as useful features. Was just scrolling through the [bootstrap components section](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/alert/) and there's lots in there too!

And ya, more key to get the functionality than the formatting, but if you see a couple examples with features/layouts that you think are cool and aren't sure which way to go with it, we can always do a group peruse through some examples (might be a worthwhile thing to do after the functionality is taking shape).

**Comment by mqharris** [comment]
I was suggesting yapf as an autoformatter

since we all have black & flake8 already installed and set up I think it makes sense to edit super-linting rather than change our setup

I pulled the branch and formatted it and many things changed. But super linter is checking things really aggressively, like its erroring on duplicate function names and it doesn't like how the modules are imported.

**Comment by sophiabulcock** [comment]
Sounds good, that was my plan for tomorrow. I might need your guys help with the formatter and getting super linter working.

**Pull request merged**
