### PR TITLE
Remove agg from altair

### PR DESCRIPTION
**Pull request by mqharris**
calculations removed from altair :

- trend line
- counts

I think thats it for all aggregates in altair

### CODE REVIEW

**Comment by WraySmith** [comment]
Looks good.

Suggest added this line of code into `app_graphing.py` between lines 23 and 24: `set_data = data.sample(frac=0.5).reset_index()`

**Comment by WraySmith** [comment]
I think the performance gains needed at this point (not for this PR but for other PR(s)) are:
- different file loading - such as using hdf5 or pickle (I've had huge gains in Shiny apps by not loading from a csv) @mqharris 
- consider changing figure 1 (which is the one that consistently lags) to a plot showing the average line of each group selecting along with a light shaded area corresponding with a quantile. The user can then use a toggle to show or hide the quantiles vs points. Points will likely always be slow but at least on load up it wouldn't be. Something for @RyKoe to consider.
- Another alternative to the above bullet point is to just to have a default that looks good when the app loads to avoid it trying to plot all points.

**Review by WraySmith — APPROVED** [review]

**Comment by mqharris** [comment]
> `set_data = data.sample(frac=0.5).reset_index()`

If we do this the graph is redrawn every time you select a different radio button with a different sample of the data.
Which leads to points subtly jumping around and sometimes the y axis is changed.

Which may confuse users

**Comment by WraySmith** [comment]
> > `set_data = data.sample(frac=0.5).reset_index()`
> 
> If we do this the graph is redrawn every time you select a different radio button with a different sample of the data.
> Which leads to points subtly jumping around and sometimes the y axis is changed.
> 
> Which may confuse users

sure, can leave it out for now

**Pull request merged**
